---
all:
  hosts:
    master:
      ansible_host: 127.0.0.1
      ansible_port: 2022
      ansible_ssh_private_key_file: id_rsa
    slave:
      ansible_host: 127.0.0.1
      ansible_port: 2033
      ansible_ssh_private_key_file: id_rsa
